/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_ouioui */

#ifndef _Included_application_ouioui
#define _Included_application_ouioui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_ouioui
 * Method:    Dijkstra
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_application_ouioui_Dijkstra
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
